<?php

class AuthorsSeeder extends BaseSeeder
{
	protected $tableName = 'authors';
	
	protected $tableColumns = array('id', 'first_name', 'middle_name', 'last_name');
	
	protected $tableValues = array(
		array(1, "Brandon", "", "Sanderson"),
		array(2, "Patrick", "", "Rothfuss"),
		array(3, "Howard", "Phillips", "Lovecraft"),
		array(4, "Peter", "", "Straub"),
		array(5, "Paolo", "", "Coello"),
		array(6, "Herman", "", "Hesse"),
		array(7, "Cormac", "", "McCarthy"),
		array(8, "Irving", "", "Stone"),
		array(9, "Richard", "", "Kacynski"),
		array(10, "Egon", "Caesar Conte", "Corti"),
		array(11, "Mortimer", "Jerome", "Adler"),
		array(12, "William", "", "Bernstein"),
		array(13, "Carrol", "", "Quigley"),
		array(14, "Will", "", "Durant"),
		array(15, "Joseph", "", "Campbell"),
		array(16, "Angel", "", "Millar"),
		array(17, "Aleister", "", "Crowley"),
		array(18, "Albert", "", "Pike"),
		array(19, "Eliphas", "", "Levi"),
		array(20, "", "", "Proclus"),
		array(21, "Michael", "", "Talbot"),
		array(22, "Martha", "", "Stout"),
		array(23, "Robert", "", "Hare"),
		array(24, "Carl", "Gustav", "Jung"),
		array(25, "Wilhelm", "", "Reich"),
		array(26, "Thomas", "", "Taylor"),
		array(27, "Alan", "", "Moore"),
		array(28, "David", "", "Lloyd"),
		array(29, "Neil", "", "Gaimon"),
		array(30, "Jamie", "", "Delano"),
		array(31, "Rick", "", "Veitch"),
		array(32, "Vishnu", "", "Devananda"),
		array(33, "Daniel", "", "Reid"),
		array(34, "Lesley", "", "Bremness"),
		array(35, "James", "F", "Balch"),
		array(36, "Phyllis", "A", "Balch"),
		array(37, "Sharon", "", "Hernandez"),
		array(38, "Ida", "", "Rodriguez"),
		array(39, "Adriana", "", "Zabarkes"),
		array(40, "Rochelle", "", "Zabarkes"),
		array(41, "Joseph", "John", "Keenan"),
		array(42, "Michael", "", "Swan"),
		array(43, "Michael", "", "Strumpf"),
		array(44, "Auriel", "", "Douglas"),
		array(45, "Greg", "", "Egan"),
		array(46, "Daniel", "", "Goleman"),
		array(47, "Kerry", "", "Patterson"),
		array(48, "Joseph", "", "Grenny"),
		array(49, "Ron", "", "McMillan"),
		array(50, "Al", "", "Switzler"),
		array(51, "Stephen", "R", "Covey"),
		array(52, "David", "", "Maxfield"),
		array(53, "Robert", "A", "Glover"),
		array(54, "Marty", "L", "Cooper"),
		array(55, "Mark", "", "Williams"),
		array(56, "John", "", "Teasdale"),
		array(57, "Zindel", "", "Segal"),
		array(58, "Jon", "", "Kabat-Zinn"),
		array(59, "James", "", "Redfield"),
		array(60, "Frederic", "", "Bastiat"),
		array(61, "David", "", "Icke"),
		array(62, "Edward", "Osborne", "Wilson"),
		array(63, "Kurt", "", "Vonnegut"),
		array(64, "Carl", "", "Sagan"),
		array(65, "Albert", "", "Einstein"),
		array(66, "Franz", "Anton", "Mesmer"),
		array(67, "George", "J", "Bloch"),
		array(68, "Ernest", "R", "Hilgard"),
		array(69, "Terence", "", "McKenna"),
		array(70, "Aldous", "", "Huxley"),
		array(71, "Jacqueline", "Hazard", "Bridgeman"),
		array(72, "Huston", "", "Smith"),
		array(73, "Spencer", "", "Johnson"),
		array(74, "Kenneth", "", "Blanchard"),
		array(75, "Bart", "D", "Ehrman"),
		array(76, "Alexander", "Sasha", "Shulgin"),
		array(77, "Ann", "", "Shulgin"),
		array(78, "Graham", "", "Hancock"),
		array(79, "Klea", "", "McKenna")
	);

	protected $emptyToNullColumns = array('first_name', 'middle_name');
}
