<?php

class BooksSeeder extends BaseSeeder
{
	protected $tableName = 'books';
	
	protected $tableColumns = array('id', 'title', 'type', 'publisher_id');
	
	protected $tableValues = array(
		array(1, "The Well of Ascension", 1, 2),
		array(2, "The Name of the Wind", 1, 3),
		array(3, "The Wise Man's Fear", 1, 3),
		array(4, "Mistborn", 1, 2),
		array(5, "The Hero of Ages", 1, 2),
		array(6, "The Complete Fiction of HP Lovecraft", 1, 1),
		array(7, "Koko", 1, 1),
		array(8, "The Alchemist", 1, 1),
		array(9, "Siddhartha", 1, 1),
		array(10, "Blood Meridien", 1, 1),
		array(11, "The Agony and the Ecstasy", 3, 1),
		array(12, "Perdurabo", 2, 1),
		array(13, "The Rise of the House of Rothschild", 2, 1),
		array(14, "The Reign of the House of Rothschild", 2, 1),
		array(15, "How to Read a Book", 2, 1),
		array(16, "The Four Pillars of Investing", 2, 1),
		array(17, "The Intelligent Asset Allocator", 2, 1),
		array(18, "Tragedy and Hope", 2, 1),
		array(19, "Our Oriental Heritage", 2, 1),
		array(20, "The Hero with a Thousand Faces", 2, 1),
		array(21, "Freemasonry: A History", 2, 1),
		array(22, "Enochian Magick", 2, 1),
		array(23, "Freemasonry", 2, 1),
		array(24, "Morals and Dogma", 2, 1),
		array(25, "Transcendental Magic", 2, 1),
		array(26, "Magick: Book 4", 2, 1),
		array(27, "The Theology of Plato", 2, 1),
		array(28, "The Holographic Universe", 2, 1),
		array(29, "The Sociopath Next Door", 2, 1),
		array(30, "Without Conscience", 2, 1),
		array(31, "Snakes in Suits", 2, 1),
		array(32, "The Basic Writings of CG Jung", 2, 1),
		array(33, "The Function of the Orgasm", 2, 1),
		array(34, "The Joint Book", 2, 1),
		array(35, "The Complete Manual of Woodworking", 2, 1),
		array(36, "V for Vendetta", 1, 1),
		array(37, "The Sandman, Volume 1: Preludes & Nocturnes", 1, 1),
		array(38, "The Sandman, Volume 2: The Doll's House", 1, 1),
		array(39, "The Sandman, Volume 3: Dream Country", 1, 1),
		array(40, "Promethea, Book 1", 1, 1),
		array(41, "Promethea, Book 2", 1, 1),
		array(42, "Promethea, Book 3", 1, 1),
		array(43, "Promethea, Book 4", 1, 1),
		array(44, "Promethea, Book 5", 1, 1),
		array(45, "The League of Extraordinary Gentlemen, Volume 1", 1, 1),
		array(46, "John Constantine, Hellblazer: (1) Original Sins", 1, 1),
		array(47, "John Constantine, Hellblazer: (2) The Devil You Know", 1, 1),
		array(48, "The Sivananda Companion to Yoga", 2, 1),
		array(49, "The Complete Book of Chinese Health and Healing", 2, 1),
		array(50, "The Complete Book of Herbs: A Practical Guide to Growing & Using Herbs", 2, 1),
		array(51, "Prescription for Nutritional Healing", 2, 1),
		array(52, "Hatch Chile Cookbook", 2, 1),
		array(53, "Adriana's Spice Caravan", 2, 1),
		array(54, "Breaking Out of Beginner's Spanish", 2, 1),
		array(55, "Practical English Usage", 2, 1),
		array(56, "The Grammar Bible", 2, 1),
		array(57, "Diaspora", 1, 1),
		array(58, "Emotional Intelligence", 2, 1),
		array(59, "Crucial Conversations: Tools for Talking When Stakes are High", 2, 1),
		array(60, "Influencer: The New Science of Leading Change", 2, 1),
		array(61, "No More Mr. Nice Guy: A Proven Plan for Getting What You Want in Love, Sex, and Life", 2, 1),
		array(62, "Anxiety and Depression: 42 Essays on Overcoming the Wild Moods", 2, 1),
		array(63, "The Mindful Way Through Depression: Freeing Yourself from Chronic Unhappiness", 2, 1),
		array(64, "The Celestine Prophecy: An Adventure", 1, 1),
		array(65, "The Law", 2, 1),
		array(66, "The David Icke Guide to the Global Conspiracy: And How to End It", 2, 1),
		array(67, "Consilience: The Unity of Knowledge", 2, 1),
		array(68, "Mysticism and the New Physics", 2, 1),
		array(69, "Quarantine", 1, 1),
		array(70, "Billions & Billions: Thoughts on Life and Death at the Brink of the Millenium", 2, 1),
		array(71, "The World As I See It", 2, 1),
		array(72, "Mesmerism: A Translation of the Original Medical and Scientific Writings of F.A. Mesmer, M.D.", 2, 1),
		array(73, "True Hallucinations: Being an Account of the Author's Extraordinary Adventures in the Devil's Paradise", 2, 1),
		array(74, "Huxley and God: Essays on Religious Experience", 2, 1),
		array(75, "The Doors of Perception / Heaven and Hell", 2, 1),
		array(76, "Brave New World", 1, 1),
		array(77, "Who Moved My Cheese?", 2, 1),
		array(78, "Misquoting Jesus: The Story Behind Who Changed the Bible and Why", 2, 1),
		array(79, "Pihkal: A Chemical Love Story", 3, 1),
		array(80, "Supernatural: Meetings with the Ancient Teachers of Mankind", 2, 1),
		array(81, "The Butterfly Hunter", 2, 1),
		array(82, "Slaughterhouse-Five", 1, 1)
	);
}
