# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	
	# General Box Settings
	config.vm.box = "ubuntu/trusty64"
	config.vm.hostname = "booknotes.dev"
	
	# Virtual Box Provider Settings
	config.vm.provider "virtualbox" do |v|
		v.memory = 2048
		v.cpus = 2
	end
	
	# Enable Host Manager on Host Machine
	config.hostmanager.manage_host = true
	
	# Provisioning Settings
	config.vm.provision "shell", path: "provision.sh"
	config.vm.provision "shell", inline: "service apache2 restart", run: "always"
	
	# Host Only Network Adaptor
	config.vm.network "private_network", ip: "192.168.56.20"
	
	# Forwarded Ports
	config.vm.network "forwarded_port", guest:80, host:8080
	config.vm.network "forwarded_port", guest:3306, host:6033

	# Shared Folders
	config.vm.synced_folder "../Application", "/var/www/booknotes", owner: "www-data", group: "vagrant", options: ["dmode=775", "fmode=664"]

end
